create table students
(
    id                        int unsigned auto_increment
        primary key,
    name                      varchar(191)         not null,
    code                      varchar(30)          not null,
    gender                    tinyint              not null comment '1 => male, 2 => female',
    birthdate                 date                 not null,
    city_id                   varchar(191)         not null,
    user_id                   int unsigned         null,
    phone_number              varchar(191)         null,
    address                   varchar(191)         null,
    about_me                  mediumtext           null,
    status                    tinyint    default 1 not null comment '0 = suspend,
1 = active,
3 = excluded,
4 = converted',
    branch_id                 int unsigned         not null,
    period tinyint not null comment '1=>morning, 2=>evening, 3=>both',
    guardian_relationship     varchar(191)         null,
    guardian_name             varchar(191)         null,
    guardian_phone_number     varchar(191)         null,
    guardian_whatsapp_number  varchar(191)         null,
    bus                       tinyint(1) default 1 not null,
    how_did_you_hear_about_us varchar(191)         null,
    personal_photo            varchar(191)         null,
    blood_type                varchar(191)         null,
    parent_id                 int unsigned         null,
    created_at                timestamp            null,
    updated_at                timestamp            null,
    email                     text                 not null,
    password                  text                 not null,
    joining_date              date                 null,
    medical_history           date                 null,
    id_number                 int                  null,
    derpatment                varchar(250)         null,
    guardian_email            varchar(250)         null,
    profession                varchar(250)         null,
    receiving_officer         varchar(250)         null,
    followup_officer          varchar(250)         null,
    appointment               date                 null,
    classroom                 text                 null,
    image                     varchar(250)         null,
    department_id             varchar(250)         null,
    birth_certificate         int                  null,
    parents_card_copy         int                  null,
    another_file              int                  null,
    level                     varchar(250)         null,
    subject_id                int                  null,
    constraint students_code_unique
        unique (code)
)
    engine = MyISAM
    collate = utf8mb4_unicode_ci;

